name: PR Labeler
on:
  pull_request:
    types: [opened]
permissions:
  contents: read

jobs:
  pr-labeler:
    name: PR Labeler
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: TimonVS/pr-labeler-action@v5
        timeout-minutes: 10
        with:
          configuration-path: .github/config/pr_labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
